FROM alpine:3.12.2 as builder

ARG perf_test_binary="target/rabbitmq-perf-test-*-bin.tar.gz"

RUN set -eux; \
	\
	apk add --no-cache --virtual .build-deps \
	    ca-certificates \
		wget \
		gnupg

ENV JAVA_VERSION="11"
ENV JAVA_SHA256="efc94aa65985153c4400a86bcbb8d86031040fd0a8f6883739f569c3a01219f8"

RUN set -eux; \
    \
    JAVA_URL="https://cdn.azul.com/zulu/bin/zulu11.45.27-ca-jdk11.0.10-linux_musl_x64.tar.gz"; \
    JAVA_PATH="/usr/lib/jdk-$JAVA_VERSION"; \
	\
    wget --progress dot:giga --output-document "$JAVA_PATH.tar.gz" "$JAVA_URL"; \
    echo "$JAVA_SHA256 *$JAVA_PATH.tar.gz" | sha256sum -c -; \
	mkdir -p "$JAVA_PATH"; \
	tar --extract --file "$JAVA_PATH.tar.gz" --directory "$JAVA_PATH" --strip-components 1; \
	$JAVA_PATH/bin/jlink --compress=2 --output /jre --add-modules java.base,java.management,java.xml,java.naming,java.sql,jdk.crypto.cryptoki; \
	/jre/bin/java -version

ENV PERF_TEST_HOME="/perf_test"
ENV PERF_TEST_PATH="/usr/local/src/perf-test"

COPY $perf_test_binary $PERF_TEST_PATH.tar.gz

RUN set -eux; \
    \
# /usr/local/src doesn't exist in Alpine by default
    mkdir -p /usr/local/src; \
    \
    mkdir -p "$PERF_TEST_HOME"; \
    tar --extract --file "$PERF_TEST_PATH.tar.gz" --directory "$PERF_TEST_HOME" --strip-components 1

FROM alpine:3.12.2

RUN apk add --no-cache bash

ENV JAVA_HOME=/usr/lib/jvm/java-1.11-zulu/jre
RUN mkdir -p $JAVA_HOME
COPY --from=builder /jre /usr/lib/jvm/java-1.11-zulu/jre/
RUN ln -svT $JAVA_HOME/bin/java /usr/local/bin/java

RUN mkdir -p /perf_test
WORKDIR /perf_test
COPY --from=builder /perf_test ./
RUN bin/runjava com.rabbitmq.perf.PerfTest --help

RUN addgroup -g 1000 perf-test
RUN adduser -u 1000 -G perf-test -D -g "perf-test user" perf-test

USER perf-test:perf-test

ENTRYPOINT ["bin/runjava", "com.rabbitmq.perf.PerfTest"]
