FROM ubuntu:20.04 as builder

ARG perf_test_binary="target/rabbitmq-perf-test-*-bin.tar.gz"

RUN set -eux; \
	\
	apt-get update; \
	apt-get install --yes --no-install-recommends \
		ca-certificates \
		wget \
		gnupg

ENV JAVA_VERSION="11"
ENV JAVA_SHA256="ae78aa45f84642545c01e8ef786dfd700d2226f8b12881c844d6a1f71789cb99"
ENV JAVA_URL="https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.10%2B9/OpenJDK11U-jdk_x64_linux_hotspot_11.0.10_9.tar.gz"

RUN set -eux; \
    \
    JAVA_PATH="/usr/lib/jdk-$JAVA_VERSION"; \
	\
    wget --progress dot:giga --output-document "$JAVA_PATH.tar.gz" "$JAVA_URL"; \
	echo "$JAVA_SHA256 *$JAVA_PATH.tar.gz" | sha256sum --check --strict -; \
	mkdir -p "$JAVA_PATH"; \
	tar --extract --file "$JAVA_PATH.tar.gz" --directory "$JAVA_PATH" --strip-components 1; \
	$JAVA_PATH/bin/jlink --compress=2 --output /jre --add-modules java.base,java.management,java.xml,java.naming,java.sql,jdk.crypto.cryptoki; \
	/jre/bin/java -version

ENV PERF_TEST_HOME="/perf_test"
ENV PERF_TEST_PATH="/usr/local/src/perf-test"

COPY $perf_test_binary $PERF_TEST_PATH.tar.gz

RUN set -eux; \
    \
    mkdir -p "$PERF_TEST_HOME"; \
    tar --extract --file "$PERF_TEST_PATH.tar.gz" --directory "$PERF_TEST_HOME" --strip-components 1

FROM ubuntu:20.04

# we need locales support for characters like µ to show up correctly in the console
RUN set -eux; \
	apt-get update; \
	apt-get install -y --no-install-recommends \
		locales \
	; \
	rm -rf /var/lib/apt/lists/*; \
	locale-gen en_US.UTF-8

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

ENV JAVA_HOME=/usr/lib/jvm/java-1.11-openjdk/jre
RUN mkdir -p $JAVA_HOME
COPY --from=builder /jre $JAVA_HOME/
RUN ln -svT $JAVA_HOME/bin/java /usr/local/bin/java

RUN mkdir -p /perf_test
WORKDIR /perf_test
COPY --from=builder /perf_test ./
RUN bin/runjava com.rabbitmq.perf.PerfTest --help

RUN groupadd --gid 1000 perf-test
RUN useradd --uid 1000 --gid perf-test --comment "perf-test user" perf-test

USER perf-test:perf-test

ENTRYPOINT ["bin/runjava", "com.rabbitmq.perf.PerfTest"]
