== Installation

=== From binary

PerfTest is distributed as a binary build archive
from https://github.com/rabbitmq/rabbitmq-perf-test/releases[GitHub releases] and
https://bintray.com/rabbitmq/java-tools/perf-test[Bintray] as well.

It is also available on
https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.rabbitmq%22%20AND%20a%3A%22perf-test%22[Maven Central]
if one needs to use it as library.

Milestone releases or release candidates are available from
https://github.com/rabbitmq/rabbitmq-perf-test/releases[GitHub releases] and from our
https://bintray.com/rabbitmq/java-tools-milestones/perf-test[Java Tools milestones repository]
as well.

The distribution contains a script (`bin/runjava` or `bin/runjava.bat`)
to run Java with the class path correctly configured, e.g.
`bin/runjava com.rabbitmq.perf.PerfTest` runs
the `PerfTest` Java class.

To verify a PerfTest installation, use:

 $ bin/runjava com.rabbitmq.perf.PerfTest --help

=== From Native Executable

PerfTest is also distributed as a native executable binary. This is an experimental
feature, see the link:#native-executable[dedicated section] for more information.

=== With Docker Image

PerfTest has a https://hub.docker.com/r/pivotalrabbitmq/perf-test/[Docker image] as well.
To us it:

 $ docker run -it --rm pivotalrabbitmq/perf-test:latest --help

Note the Docker container needs to be able to contact the host where the broker runs.
Please see the https://docs.docker.com/network/[Docker network documentation]
to find out more about this topic. Once network access is sorted out, PerfTest options
can be used normally, e.g.:

 $ docker run -it --rm pivotalrabbitmq/perf-test:latest -x 1 -y 2 \
    -u "throughput-test-1" -a --id "test 1"

[NOTE]
====
If both the broker and the container run on the machine, the following Docker options
can be useful for Linux hosts:

 $ docker run -it --rm --network host pivotalrabbitmq/perf-test:latest

Note the use of the https://docs.docker.com/network/host/[`host` network driver].
This does not work on macOS but a https://docs.docker.com/docker-for-mac/networking/[workaround]
exists:

 $ docker run -it --rm pivotalrabbitmq/perf-test:latest -h amqp://host.docker.internal

The special DNS name `host.docker.internal` resolves to the internal IP address used by the host.
====

=== For Cloud Foundry

There is a https://github.com/rabbitmq/rabbitmq-perf-test-for-cf[template project]
to easily run PerfTest on https://www.cloudfoundry.org/[Cloud Foundry].


