== Installation

=== From Binary

PerfTest is distributed as a binary build archive
from https://github.com/rabbitmq/rabbitmq-perf-test/releases[GitHub releases] and
https://bintray.com/rabbitmq/java-tools/perf-test[Bintray] as well.

It is also available on
https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.rabbitmq%22%20AND%20a%3A%22perf-test%22[Maven Central]
if one needs to use it as library.

Milestone releases or release candidates are available from
https://github.com/rabbitmq/rabbitmq-perf-test/releases[GitHub releases] and from our
https://bintray.com/rabbitmq/java-tools-milestones/perf-test[Java Tools milestones repository]
as well.

The distribution contains a script (`bin/runjava` or `bin/runjava.bat`)
to run Java with the class path correctly configured, e.g.
`bin/runjava com.rabbitmq.perf.PerfTest` runs
the `PerfTest` Java class.

To verify a PerfTest installation, use:

 bin/runjava com.rabbitmq.perf.PerfTest --help

=== From Native Executable

PerfTest is also distributed as a native executable binary. This is an experimental
feature, see the <<native-executable,dedicated section>> for more information.

=== From Docker Image

PerfTest has a https://hub.docker.com/r/pivotalrabbitmq/perf-test/[Docker image] as well.
To use it:

 docker run -it --rm pivotalrabbitmq/perf-test:latest --help

Note that the Docker container needs to be able to connect to the host where
the RabbitMQ broker runs.  Find out more at
https://docs.docker.com/network/[Docker network documentation].  Once the
Docker container where PerfTest runs can connect to the RabbitMQ broker,
PerfTest can be run with the regular options, e.g.:

 docker run -it --rm pivotalrabbitmq/perf-test:latest -x 1 -y 2 -u "throughput-test-1" -a --id "test 1"

To run the RabbitMQ broker within Docker, and run PerfTest against it, run the
following commands:

 docker network create perf-test
 docker run -it --rm --network perf-test --name rabbitmq -p 15672:15672 rabbitmq:3.8.2-management
 docker run -it --rm --network perf-test pivotalrabbitmq/perf-test:latest --uri amqp://rabbitmq

=== For Cloud Foundry

There is a https://github.com/rabbitmq/rabbitmq-perf-test-for-cf[template project]
to easily run PerfTest on https://www.cloudfoundry.org/[Cloud Foundry].


