#!/bin/sh

set -e

SCRIPTDIR=$(dirname "$0")
SRCDIR=$(cd "$SCRIPTDIR"/.. && pwd)

(
	cd "$SRCDIR"
	mvn -q compile
	mvn -q exec:java \
		-Dexec.mainClass="com.rabbitmq.perf.PerfTest" -Dexec.args="$*"
)
